# Generated by Django 5.2.14 on 2026-05-23 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductorAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(limit_choices_to={'rol': 'AGENTE_ANDINO'}, on_delete=django.db.models.deletion.CASCADE, related_name='productores_asignados', to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(limit_choices_to={'rol': 'PRODUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='agente_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productor asignado',
                'verbose_name_plural': 'Productores asignados',
                'unique_together': {('agente', 'productor')},
            },
        ),
    ]
