# Generated by Django 5.2.14 on 2026-05-24 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_actaverificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorasignado',
            options={},
        ),
        migrations.RemoveField(
            model_name='productorasignado',
            name='notas',
        ),
        migrations.AlterField(
            model_name='actaverificacion',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actaverificacion',
            name='hash_validacion',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='productorasignado',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productores_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorasignado',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolicitudRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('iniciador', 'receptor')},
            },
        ),
        migrations.AddField(
            model_name='productorasignado',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relacion_activa', to='agente.solicitudrelacion'),
        ),
    ]
