# Generated by Django 5.2.14 on 2026-05-24 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CONFIRMADO', 'Confirmado por comprador'), ('DISPUTADO', 'En disputa'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE_PAGO', max_length=20)),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('direccion_entrega', models.TextField()),
                ('notas', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_orden', to='marketplace.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orden')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado_por_agente', models.BooleanField(default=False)),
                ('confirmado_por_comprador', models.BooleanField(default=False)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='entregas/')),
                ('notas_entrega', models.TextField(blank=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion', to='orders.orden')),
            ],
        ),
        migrations.CreateModel(
            name='PagoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('TARJETA', 'Tarjeta de crédito/débito'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia bancaria')], max_length=20)),
                ('estado', models.CharField(choices=[('RETENIDO', 'Retenido (escrow)'), ('LIBERADO', 'Liberado al productor'), ('DEVUELTO', 'Devuelto al comprador')], default='RETENIDO', max_length=15)),
                ('codigo_confirmacion', models.CharField(editable=False, max_length=64, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='orders.orden')),
            ],
        ),
    ]
